{
 "title": "IBAN Validation API",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "API Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API request count",
   "type": "timeseries",
   "description": "The count of API requests per second",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(iban_validation_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request by status/method",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[1m])",
     "legendFormat": "{{status}} -  {{method}}"
    }
   ]
  },
  {
   "title": "External: IBAN Api (api.ibanapi.com)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Credit Balance",
   "type": "timeseries",
   "description": "A \"bank\" balance is required for a BLZ query for IBANs outside Germany.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "sum(ibanapi_balance_bank)", "legendFormat": "Bank" },
    { "expr": "sum(ibanapi_balance_basic)", "legendFormat": "Basic" }
   ]
  },
  {
   "title": "Number of remaining BLZ lookups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ibanapi_balance_bank)", "legendFormat": "Bank" },
    { "expr": "sum(ibanapi_balance_basic)", "legendFormat": "Basic" }
   ]
  },
  {
   "title": "HTTP response status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "increase(iban_validation_blz_fallback_request_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}